return {
	[1] = {
		["type"] = 1,
		["name"] = "Manual Upgrade",
		["id"] = 1,
		["initialExp"] = 10,
		["initialRate"] = 1,
	},
	[2] = {
		["type"] = 2,
		["name"] = "Automatic Upgrade 1",
		["id"] = 2,
		["initialExp"] = 10,
		["initialRate"] = 1,
	},
	[3] = {
		["type"] = 2,
		["name"] = "Automatic Upgrade 3",
		["id"] = 3,
		["initialExp"] = 10,
		["initialRate"] = 1,
	},
	[4] = {
		["type"] = 2,
		["name"] = "Automatic Upgrade 5",
		["id"] = 4,
		["initialExp"] = 10,
		["initialRate"] = 1,
	},
	[5] = {
		["type"] = 3,
		["name"] = "Place Upgrade 5",
		["id"] = 5,
		["initialExp"] = 10,
		["initialRate"] = 1,
	},
}