return {
	[1] = {
		["id"] = 1,
		["coinBonusPercent"] = 50,
		["name_t"] = "Gold",
		["resourceName"] = "FX04_04",
	},
	[2] = {
		["id"] = 2,
		["coinBonusPercent"] = 100,
		["name_t"] = "Miasma",
		["resourceName"] = "FX02_03",
	},
	[3] = {
		["id"] = 3,
		["coinBonusPercent"] = 300,
		["name_t"] = "Flux",
		["resourceName"] = "FX03_05",
	},
	[4] = {
		["id"] = 4,
		["coinBonusPercent"] = 500,
		["name_t"] = "Volt",
		["resourceName"] = "FX01_10",
	},
	[5] = {
		["id"] = 5,
		["coinBonusPercent"] = 700,
		["name_t"] = "Loop",
		["resourceName"] = "FX04_02",
	},
	[6] = {
		["id"] = 6,
		["coinBonusPercent"] = 1100,
		["name_t"] = "Phantom",
		["resourceName"] = "FX02_06",
	},
	[7] = {
		["id"] = 7,
		["coinBonusPercent"] = 1500,
		["name_t"] = "Prism",
		["resourceName"] = "FX03_09",
	},
	[8] = {
		["id"] = 8,
		["coinBonusPercent"] = 3900,
		["name_t"] = "Blast",
		["resourceName"] = "FX01_07",
	},
	[9] = {
		["id"] = 9,
		["coinBonusPercent"] = 4900,
		["name_t"] = "Orbit",
		["resourceName"] = "FX04_01",
	},
	[10] = {
		["id"] = 10,
		["coinBonusPercent"] = 9900,
		["name_t"] = "Ember",
		["resourceName"] = "FX02_08",
	},
}