return {
	[1] = {
		["buffValue"] = 2,
		["describe_t"] = "Double your exercise speed",
		["buffType"] = 1,
		["id"] = 1,
		["iconImageId"] = "rbxassetid://17127979242",
		["name_t"] = "X2 Exercise Efficiency",
		["buffMethod"] = 1,
	},
	[2] = {
		["buffValue"] = 2,
		["describe_t"] = "Gold coin earnings doubled",
		["buffType"] = 2,
		["id"] = 2,
		["iconImageId"] = "rbxassetid://77129516059952",
		["name_t"] = "X2 Coin",
		["buffMethod"] = 1,
	},
	[3] = {
		["buffValue"] = 0,
		["describe_t"] = "Friends Online Buff: Gold Earnings +{1}",
		["buffType"] = 2,
		["id"] = 3,
		["iconImageId"] = "rbxassetid://137369651578048",
		["name_t"] = "FriendReward",
		["buffMethod"] = 3,
	},
}