return {
	[1] = {
		["buffValue"] = 2,
		["describe_t"] = "Double your exercise speed",
		["buffType"] = 1,
		["id"] = 1,
		["iconImageId"] = "rbxassetid://17127979242",
		["name_t"] = "X2 Exercise Efficiency",
		["buffMethod"] = 1,
	},
	[2] = {
		["buffValue"] = 2,
		["describe_t"] = "Gold coin earnings doubled",
		["buffType"] = 2,
		["id"] = 2,
		["iconImageId"] = "rbxassetid://77129516059952",
		["name_t"] = "X2 Coin",
		["buffMethod"] = 1,
	},
}