return {
	[1] = {
		["id"] = 1,
		["name_t"] = "Zone0",
		["resourceName"] = "Zone0",
	},
	[2] = {
		["id"] = 2,
		["name_t"] = "Zone1",
		["resourceName"] = "Zone1",
	},
	[3] = {
		["id"] = 3,
		["name_t"] = "Zone2",
		["resourceName"] = "Zone2",
	},
	[4] = {
		["id"] = 4,
		["name_t"] = "Zone3",
		["resourceName"] = "Zone3",
	},
	[5] = {
		["id"] = 5,
		["name_t"] = "Zone4",
		["resourceName"] = "Zone4",
	},
	[6] = {
		["id"] = 6,
		["name_t"] = "Zone5",
		["resourceName"] = "Zone5",
	},
	[7] = {
		["id"] = 7,
		["name_t"] = "Zone6",
		["resourceName"] = "Zone6",
	},
	[8] = {
		["id"] = 8,
		["name_t"] = "Zone7",
		["resourceName"] = "Zone7",
	},
	[9] = {
		["id"] = 9,
		["name_t"] = "Zone8",
		["resourceName"] = "Zone8",
	},
	[10] = {
		["id"] = 10,
		["name_t"] = "Zone9",
		["resourceName"] = "Zone9",
	},
	[11] = {
		["id"] = 11,
		["name_t"] = "Zone10",
		["resourceName"] = "Zone10",
	},
	[12] = {
		["id"] = 12,
		["name_t"] = "Zone11",
		["resourceName"] = "Zone11",
	},
	[13] = {
		["id"] = 13,
		["name_t"] = "Zone12",
		["resourceName"] = "Zone12",
	},
	[14] = {
		["id"] = 14,
		["name_t"] = "Zone13",
		["resourceName"] = "Zone13",
	},
	[15] = {
		["id"] = 15,
		["name_t"] = "Zone14",
		["resourceName"] = "Zone14",
	},
	[16] = {
		["id"] = 16,
		["name_t"] = "Zone15",
		["resourceName"] = "Zone15",
	},
	[17] = {
		["id"] = 17,
		["name_t"] = "Zone16",
		["resourceName"] = "Zone16",
	},
	[18] = {
		["id"] = 18,
		["name_t"] = "Zone17",
		["resourceName"] = "Zone17",
	},
	[19] = {
		["id"] = 19,
		["name_t"] = "Zone18",
		["resourceName"] = "Zone18",
	},
	[20] = {
		["id"] = 20,
		["name_t"] = "Zone19",
		["resourceName"] = "Zone19",
	},
	[21] = {
		["id"] = 21,
		["name_t"] = "Zone20",
		["resourceName"] = "Zone20",
	},
	[22] = {
		["id"] = 22,
		["name_t"] = "Zone21",
		["resourceName"] = "Zone21",
	},
	[23] = {
		["id"] = 23,
		["name_t"] = "Zone22",
		["resourceName"] = "Zone22",
	},
	[24] = {
		["id"] = 24,
		["name_t"] = "Zone23",
		["resourceName"] = "Zone23",
	},
	[25] = {
		["id"] = 25,
		["name_t"] = "Zone24",
		["resourceName"] = "Zone24",
	},
	[26] = {
		["id"] = 26,
		["name_t"] = "Zone25",
		["resourceName"] = "Zone25",
	},
	[27] = {
		["id"] = 27,
		["name_t"] = "Zone26",
		["resourceName"] = "Zone26",
	},
	[28] = {
		["id"] = 28,
		["name_t"] = "Zone27",
		["resourceName"] = "Zone27",
	},
	[29] = {
		["id"] = 29,
		["name_t"] = "Zone28",
		["resourceName"] = "Zone28",
	},
	[30] = {
		["id"] = 30,
		["name_t"] = "Zone29",
		["resourceName"] = "Zone29",
	},
	[31] = {
		["id"] = 31,
		["name_t"] = "Zone30",
		["resourceName"] = "Zone30",
	},
	[32] = {
		["id"] = 32,
		["name_t"] = "Zone31",
		["resourceName"] = "Zone31",
	},
	[33] = {
		["id"] = 33,
		["name_t"] = "Zone32",
		["resourceName"] = "Zone32",
	},
	[34] = {
		["id"] = 34,
		["name_t"] = "Zone33",
		["resourceName"] = "Zone33",
	},
	[35] = {
		["id"] = 35,
		["name_t"] = "Zone34",
		["resourceName"] = "Zone34",
	},
	[36] = {
		["id"] = 36,
		["name_t"] = "Zone35",
		["resourceName"] = "Zone35",
	},
	[37] = {
		["id"] = 37,
		["name_t"] = "Zone36",
		["resourceName"] = "Zone36",
	},
	[38] = {
		["id"] = 38,
		["name_t"] = "Zone37",
		["resourceName"] = "Zone37",
	},
	[39] = {
		["id"] = 39,
		["name_t"] = "Zone38",
		["resourceName"] = "Zone38",
	},
	[40] = {
		["id"] = 40,
		["name_t"] = "Zone39",
		["resourceName"] = "Zone39",
	},
	[41] = {
		["id"] = 41,
		["name_t"] = "Zone40",
		["resourceName"] = "Zone40",
	},
	[42] = {
		["id"] = 42,
		["name_t"] = "Zone41",
		["resourceName"] = "Zone41",
	},
	[43] = {
		["id"] = 43,
		["name_t"] = "Zone42",
		["resourceName"] = "Zone42",
	},
	[44] = {
		["id"] = 44,
		["name_t"] = "Zone43",
		["resourceName"] = "Zone43",
	},
	[45] = {
		["id"] = 45,
		["name_t"] = "Zone44",
		["resourceName"] = "Zone44",
	},
	[46] = {
		["id"] = 46,
		["name_t"] = "Zone45",
		["resourceName"] = "Zone45",
	},
	[47] = {
		["id"] = 47,
		["name_t"] = "Zone46",
		["resourceName"] = "Zone46",
	},
	[48] = {
		["id"] = 48,
		["name_t"] = "Zone47",
		["resourceName"] = "Zone47",
	},
}